language: java
sudo: false
jdk:
- openjdk7
env:
  global:
    secure: VBbn9U0cmkvUFc4oIrSIkwZArfrSRTYgXZ1nK63D3uBlwI7S6Ibw2ketwT4Mke6uHj2Vn6wrhsNyTtozplPOq7pZrAYEXyFyAAgwDOUkIwn7GG1EEtbfH5E5lgrEtTmrx0TQQ/zBWClP6qTfkAFQsiC9G8eKIv4GjR2MeOgXtRW1pvWHAqgXZwsj6i/sS3+qIcYlF0TN5as4eN7kkV0V2VXqQjofjzFuV9NJ337tbPmIHLFAPJGEyAGy/GviPIzZZ4AaMpuSGj/XrdoFYDxYPatqzoXn7rj4CU9ieB6L3RpAbRu1se278a7qYU42ayUMpJtyo911CIJiH6XI3dIYpaevA7m8sOLtM9hNaBiqC9EgKp59BR8Fq+0NMfDCyubs88DLW+YgOn4rssrpmyOqT1fwRdrm4PpHFGtmZEUY/MmLIKaJDgr1oJgGb+XF0k1a6IUupdlkckBMzdDlwMZtejfYFvi5T2VpOZaSFQjPIpPt7RyGwT7l11itKR2YOcgzCCqh/BrAQsOAs4kns0/ISrvOLBOvSpUGWUVVtHkJipqqyYlNlUXaTqFs+ZQawlSkThxEWR1JihQrH00jynZMv2H0xTX5Wf4KEjytVbV4OuVvlGNzeQdXrVj6E3bvh53EJc7bkkEUZbiNTnOpUPUrgBzjA+JDKmR7FnLotq38CQM= # COVERALLS_REPO_TOKEN
script: mvn clean test jacoco:report coveralls:report
deploy:
  provider: releases
  prerelease: false
  api_key:
    secure: DdABs6v/PtP/6lPm2s0ZsmxzDlBD+QrvqzsLba+kEPGG7mfMXP7jw05rRL+eV4gex4pQCtc5oFaRhUP1nZaNRXMhq/Y0GL6OiZ0U/YBfxb225nSCSUnEQ/EDTQWVeBSrZCkvAOmm1jcyr+K8M4+QGsLa+CWlOvVMUSCtUkA75ZefB+DoeUa6G06uLNYQvY7PufLBToQAzPSdLZE4tDL/+8PEFImo4+ZW08s9liI12HNxbyLw2s2nSG7V25FoeU+ckTSWX85ajRJ5Qmn0E+rMjRbGK2ds4Znuq20l6gl5UtDhkzYCMIBQuFglqfSqJtNcSMsYKlMjqziJGFpuHoblXNVN8L230pxjEU4p9XoOPa9cUurEH1X1LzxTUmxVHl8ZXzqUf6d0MSJJWxRwck47bfBAnZT0mfeoFvFoYHgna0ySKrBNnUb6YZnejAkfvu3YBmEaTN00wKYfU4kQefLrOxgsQEYsDKd8pE9m8E2PxkM25iKg9h6Pi4Bk4GRT0eaR8r2yxM5VmVYZTs0btq820YB+aa0qHimeGzNmeQRwgo3yoz2BJKpRXacbrhx6LPRA3AUERdgMThnKU9o0QpWgyjo/imGrCUPSaqnyzm/AjGyiZANqpt/KBbQuGDgVV1j094tuKjnDv6qQMTuMqAmA8Ep4xbctbs3/BvMPK3QovRM= # GitHub releases
  file_glob: true
  file: target/cryptolib-*.jar
  skip_cleanup: true
  on:
    repo: cryptomator/cryptolib
    tags: true
