language: java
sudo: false
jdk:
- openjdk7
env:
  global:
  - secure: VBbn9U0cmkvUFc4oIrSIkwZArfrSRTYgXZ1nK63D3uBlwI7S6Ibw2ketwT4Mke6uHj2Vn6wrhsNyTtozplPOq7pZrAYEXyFyAAgwDOUkIwn7GG1EEtbfH5E5lgrEtTmrx0TQQ/zBWClP6qTfkAFQsiC9G8eKIv4GjR2MeOgXtRW1pvWHAqgXZwsj6i/sS3+qIcYlF0TN5as4eN7kkV0V2VXqQjofjzFuV9NJ337tbPmIHLFAPJGEyAGy/GviPIzZZ4AaMpuSGj/XrdoFYDxYPatqzoXn7rj4CU9ieB6L3RpAbRu1se278a7qYU42ayUMpJtyo911CIJiH6XI3dIYpaevA7m8sOLtM9hNaBiqC9EgKp59BR8Fq+0NMfDCyubs88DLW+YgOn4rssrpmyOqT1fwRdrm4PpHFGtmZEUY/MmLIKaJDgr1oJgGb+XF0k1a6IUupdlkckBMzdDlwMZtejfYFvi5T2VpOZaSFQjPIpPt7RyGwT7l11itKR2YOcgzCCqh/BrAQsOAs4kns0/ISrvOLBOvSpUGWUVVtHkJipqqyYlNlUXaTqFs+ZQawlSkThxEWR1JihQrH00jynZMv2H0xTX5Wf4KEjytVbV4OuVvlGNzeQdXrVj6E3bvh53EJc7bkkEUZbiNTnOpUPUrgBzjA+JDKmR7FnLotq38CQM= # COVERALLS_REPO_TOKEN
  - secure: XUA3IT49IuSjdIsY2DVqyU7rR8VlzLUbb+/guVt4oMGarjFvMqpC6bSLhPABsDPN7x5hke1FZp8Nghxe1kC6KvJAI8t/HAbUXIUpUQcz0iOH6LNoZfwvO6imBQWbvZnWIngXNI6vtnBLgh94KiJ+1hklbgxIg97YSuhcbNO6vcS1RdF2Re5aCUjkn0FsrDmcD4T0hK6cvJKDNAyfVVuuz7BiwJejgFWTcNX6Q+MERiuuitM+Va1M30qmk/Lw/MkAe/m7RyrH1C8apBLoNmL3hl0IMh7poewK8PpWkiUvuSz7zwuw/xSsIGoOWkp1eF4hdF/3oi203hYRJJYt93GjHwLCO5ckToMr2DkDWJdsr+PC5PJ17/+jiFA+3CwpkQoIIzphUpa4VgnfrF3FHrawhg2cNQC+1zaQMsw+r40EJknRiMV9I0Uit9rLGATa3HP3ltt/WFIyVuSFnFIoa/G2UBAoXuuvs6ekgdQwQ1U4Wf2wS4QJzFLVsB/qsbhA4mOiyNCGHE1ubVw75GY0OWs7aOa7lPZ2QYEyBKSZ8VaKrSWzXoix+9YdC7AmD8vX8ZBSQaVFFO9EKEIY3+zte+nO7x4dIH/JYD2m4edaRuPddwcYZuobI99hSLTNmJHCBDRBZsDF1PgN4okvHLqMTbJLbl/M37qbrdgxxnlFcE/jiZI= # COVERITY_SCAN_TOKEN
script: "mvn clean test jacoco:report coveralls:report"
addons:
  coverity_scan:
    project:
      name: "cryptomator/cryptolib"
      description: "Build submitted via Travis CI"
    notification_email: sebastian.stenzel@cryptomator.org
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: master
deploy:
  provider: releases
  prerelease: false
  api_key:
    secure: DdABs6v/PtP/6lPm2s0ZsmxzDlBD+QrvqzsLba+kEPGG7mfMXP7jw05rRL+eV4gex4pQCtc5oFaRhUP1nZaNRXMhq/Y0GL6OiZ0U/YBfxb225nSCSUnEQ/EDTQWVeBSrZCkvAOmm1jcyr+K8M4+QGsLa+CWlOvVMUSCtUkA75ZefB+DoeUa6G06uLNYQvY7PufLBToQAzPSdLZE4tDL/+8PEFImo4+ZW08s9liI12HNxbyLw2s2nSG7V25FoeU+ckTSWX85ajRJ5Qmn0E+rMjRbGK2ds4Znuq20l6gl5UtDhkzYCMIBQuFglqfSqJtNcSMsYKlMjqziJGFpuHoblXNVN8L230pxjEU4p9XoOPa9cUurEH1X1LzxTUmxVHl8ZXzqUf6d0MSJJWxRwck47bfBAnZT0mfeoFvFoYHgna0ySKrBNnUb6YZnejAkfvu3YBmEaTN00wKYfU4kQefLrOxgsQEYsDKd8pE9m8E2PxkM25iKg9h6Pi4Bk4GRT0eaR8r2yxM5VmVYZTs0btq820YB+aa0qHimeGzNmeQRwgo3yoz2BJKpRXacbrhx6LPRA3AUERdgMThnKU9o0QpWgyjo/imGrCUPSaqnyzm/AjGyiZANqpt/KBbQuGDgVV1j094tuKjnDv6qQMTuMqAmA8Ep4xbctbs3/BvMPK3QovRM= # GitHub releases
  file_glob: true
  file: target/cryptolib-*.jar
  skip_cleanup: true
  on:
    repo: cryptomator/cryptolib
    tags: true
